services:
  mongodb:
    build: ./db
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - '27017:27017'
    networks:
      - mat-network
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - image_data:/app/images
    environment:
      - DBURI=${DBURI}
      - MICROSOFT_ISSUER_URL=${MICROSOFT_ISSUER_URL}
      - MICROSOFT_APP_ID=${MICROSOFT_APP_ID}
      - PORT=${PORT}
      - CSRF_SECRET=${CSRF_SECRET}
    ports:
      - "5000:5000"
    networks:
      - mat-network
    depends_on:
      - mongodb
    command: ["npm", "run", "start"]
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BE_URL=${VITE_BE_URL}
        - VITE_MS_TENANT=${MICROSOFT_TENANT}
        - VITE_MS_APP_ID=${MICROSOFT_APP_ID}
    ports:
      - "3000:3000"
    networks:
      - mat-network
    command: ["npm", "run", "start"]
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mat-network
    depends_on:
      - frontend
      - backend
    restart: always

networks:
  mat-network:
    driver: bridge

volumes:
  mongo_data:
  mongo_config:
  image_data:
